default_platform(:ios)

def api_key
  app_store_connect_api_key(
    key_id: json["key_id"],
    issuer_id: json["issuer_id"],
    key_filepath: json["key_filepath"]
  )
end

def json
  @json ||= JSON.parse(File.read("api_key.json"))
end

platform :ios do
  desc "Run macOS tests"
  lane :test_mac do
    run_tests(
      scheme: "StandBy",
      destination: "platform=macOS",
      clean: true
    )
  end

  desc "Run watchOS tests"
  lane :test_watch do
    run_tests(
      scheme: "StandByWatch",
      destination: "platform=watchOS Simulator,name=Apple Watch Series 11 (46mm)",
      clean: true
    )
  end

  desc "Create app on App Store Connect"
  lane :create_app do |options|
    api_key
    produce(
      app_identifier: options[:app_identifier],
      app_name: options[:app_name],
      skip_itc: false,
      skip_devcenter: false
    )
  end

  desc "Upload watchOS app to TestFlight"
  lane :beta_watch do
    build_app(
      scheme: "StandByWatchContainer",
      destination: "generic/platform=iOS",
      export_method: "app-store",
      clean: true,
      xcargs: "-allowProvisioningUpdates",
      export_options: {
        signingStyle: "automatic",
        teamID: "AZ28EH9G9N"
      }
    )
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end

  desc "Upload macOS app to TestFlight"
  lane :beta_mac do
    build_mac_app(
      scheme: "StandBy",
      export_method: "app-store",
      clean: true
    )
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
